GET http://localhost:8080/clases 
### 
GET http://localhost:8080/clases/7
###
POST http://localhost:8080/clases
Content-Type: application/json 

{
  "nombre": "CROSSFIT",
  "descripcion": "Entrenamiento de alta intensidad",
  "diaSemana": "MIERCOLES",
  "horario": "17:00:00",
  "capacidad": 22
}
### 
PUT http://localhost:8080/clases/9
Content-Type: application/json 

{
  "nombre": "Funcional",
  "descripcion": "Ejercicios de cuerpo completo",
  "diaSemana": "VIERNES",
  "horario": "17:00:00",
  "capacidad": 20
}
### 
DELETE http://localhost:8080/clases/1